### ISSUE TITLE
Error in loading json file

### ISSUE THREAD

**Issue by TianjinYellow** [pixeli99/OwLore#2]
**Hi,
when i run bash owlore_scripts/run_owlore_low_rank.sh mmlu, i encountered the below error, do you know how to solve it. BTW, is there a script for downloading your datasets?
Best** 

en=False, disable_conversation_eos_token=False, conversation_template='empty')
single file /gpfs/home2/huangti/Projects/OwLore/data/gsm/gsm8k.json
Traceback (most recent call last):
  File "/gpfs/home2/huangti/Projects/OwLore/examples/finetune.py", line 62, in <module>
    main()
  File "/gpfs/home2/huangti/Projects/OwLore/examples/finetune.py", line 54, in main
    dataset = Dataset(data_args)
              ^^^^^^^^^^^^^^^^^^
  File "/gpfs/home2/huangti/Projects/OwLore/src/lmflow/datasets/dataset.py", line 82, in __init__
    json_data = json.load(fin)
                ^^^^^^^^^^^^^^
  File "/home/huangti/miniconda3/envs/ft/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/home/huangti/miniconda3/envs/ft/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangti/miniconda3/envs/ft/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/huangti/miniconda3/envs/ft/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):

**Comment by pixeli99** [comment]
Hi, @TianjinYellow ,

Sorry for the late reply,

Did you download the dataset from here, https://huggingface.co/datasets/pengxiang/OwLore_Dataset? This Hugging Face space contains all the datasets we use.

**Comment by h0ngxuanli** [comment]
Directly git clone dataset from huggingface may lead to empty dataset. Manually downloading could solve this issue.
